packages:
  - 'apps/*'
  - 'packages/*'
  - 'frontend'
  - 'modules/pos/*'
  - 'modules/pos/pos-backend'
  - 'modules/pos/pos-frontend'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
