kind = "web"
previewPath = "/"
title = "Form Registrasi Event"
version = "1.0.0"
id = "artifacts/event-registration"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23287

[services.development]
run = "pnpm --filter @workspace/event-registration run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/event-registration", "run", "build" ]
publicDir = "artifacts/event-registration/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23287"
BASE_PATH = "/"
