<?php

return [
    'version' => env('SIDEBAR_CONFIG_VERSION', '2026-05-12'),
    'source' => 'config/sidebar.php',
    'description' => 'Single source of truth for ERP sidebar configuration and grouping metadata.',

    'groups' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'active_patterns' => [
                '/',
                'erp/owner-dashboard',
                'erp/analytics',
                'erp/multi-branch-analytics',
                'erp/ai-analytics',
            ],
        ],

        'sales' => [
            'label' => 'Sales',
            'active_patterns' => [
                'po-form',
                'erp/invoice',
                'erp/riwayat-penjualan',
                'erp/quotation',
                'erp/sales-order',
                'erp/delivery-order',
                'erp/order-tracking',
                'erp/sales-target',
                'erp/sales-commission',
                'erp/sales-receivable',
                'erp/retur',
                'erp/discount',
                'erp/membership',
                'erp/installment',
                'erp/installment-due',
                'erp/price-types',
            ],
        ],

        'inventory' => [
            'label' => 'Inventory',
            'active_patterns' => [
                'products',
                'erp/stock-opname',
                'erp/warehouse',
                'erp/multi-warehouse',
                'erp/rack',
                'erp/stock-in',
                'erp/stock-out',
                'erp/stock-mutation',
                'erp/warehouse-transfer',
                'erp/stock-adjustment',
                'erp/stock-card',
                'erp/min-stock',
                'erp/stock-history',
                'erp/serial-number',
                'erp/product-batch',
                'erp/product-categories',
                'erp/brands',
                'erp/sku',
                'erp/barcode',
                'erp/units',
                'erp/inventory-value',
                'erp/fast-moving',
                'erp/slow-moving',
                'erp/production',
                'erp/assembly',
                'erp/production-formula',
            ],
        ],

        'purchase' => [
            'label' => 'Purchase',
            'active_patterns' => [
                'erp/supplier',
                'erp/purchase-order',
                'erp/goods-receipt',
                'erp/purchase-request',
                'erp/purchase-approval',
                'erp/supplier-invoice',
                'erp/purchase-return',
                'erp/account-payable',
                'erp/payable-due',
                'erp/pay-supplier',
                'erp/supplier-analytics',
            ],
        ],

        'finance' => [
            'label' => 'Finance',
            'active_patterns' => [
                'erp/cash-in',
                'erp/cash-out',
                'erp/main-cash',
                'erp/petty-cash',
                'erp/electronic-cash',
                'erp/building-cash',
                'erp/bank-account',
                'erp/bank-transfer',
                'erp/giro',
                'erp/expense',
                'erp/profit-loss',
                'erp/bank-reconciliation',
                'erp/multi-currency',
                'erp/cash-flow',
            ],
        ],

        'accounting' => [
            'label' => 'Accounting',
            'active_patterns' => [
                'erp/chart-of-accounts',
                'erp/journal',
                'erp/general-ledger',
                'erp/trial-balance',
                'erp/balance-sheet',
                'erp/opening-balance',
                'erp/accounting-period',
                'erp/departments',
                'erp/projects',
                'erp/budgeting',
                'erp/audit-transaction',
                'erp/approval-system',
            ],
        ],

        'tax' => [
            'label' => 'Tax',
            'active_patterns' => [
                'erp/taxes',
                'erp/multi-tax',
                'erp/vat',
                'erp/pph',
                'erp/tax-invoice',
                'erp/e-faktur',
                'erp/tax-report',
                'erp/tax-accounting',
            ],
        ],

        'crm' => [
            'label' => 'CRM',
            'active_patterns' => [
                'erp/customers',
                'erp/customer-group',
                'erp/customer-credit',
                'erp/customer-history',
                'erp/loyalty',
                'erp/customer-followup',
                'erp/whatsapp-blast',
                'erp/payment-reminder',
                'erp/customer-complaint',
                'erp/chatbot-ai',
            ],
        ],

        'delivery' => [
            'label' => 'Delivery',
            'active_patterns' => [
                'admin',
                'driver',
                'erp/delivery-note',
                'erp/tracking',
                'erp/delivery-proof',
                'erp/delivery-schedule',
                'erp/fleet',
                'erp/drivers',
            ],
        ],

        'marketplace' => [
            'label' => 'Marketplace',
            'active_patterns' => [
                'marketplace',
                'erp/marketplace-overview',
                'erp/marketplace-sync',
                'erp/multi-channel-order',
                'erp/multi-channel-chat',
                'erp/multi-channel-analytics',
                'erp/marketplace-realtime',
                'erp/shopee/*',
                'erp/tiktok/*',
                'erp/tokopedia/*',
                'erp/lazada/*',
            ],
        ],

        'service' => [
            'label' => 'Service',
            'active_patterns' => [
                'erp/service',
                'erp/warranty',
                'erp/service-tracking',
                'erp/sparepart',
                'erp/technician',
                'erp/service-schedule',
                'erp/service-history',
            ],
        ],

        'reports' => [
            'label' => 'Reports',
            'active_patterns' => [
                'erp/laporan-penjualan',
                'erp/laporan-divisi',
                'erp/data-penjualan-kledo',
                'erp/report-finance',
                'erp/report-driver',
                'erp/report-purchase',
                'erp/report-inventory',
                'erp/report-tax',
                'erp/profit-product',
                'erp/profit-branch',
                'erp/sales-trend',
                'erp/export-pdf',
                'erp/export-excel',
                'erp/analytics',
                'erp/ai-analytics',
                'erp/multi-branch',
            ],
        ],

        'ai' => [
            'label' => 'AI & Automation',
            'active_patterns' => [
                'erp/ai-inventory',
                'erp/chatbot',
                'erp/chatbot-ai',
                'erp/forecasting',
                'erp/workflow-automation',
                'erp/approval-workflow',
                'erp/auto-reminder',
                'erp/auto-sync',
            ],
        ],

        'hrd' => [
            'label' => 'HRD',
            'active_patterns' => [
                'erp/employees',
                'erp/attendance',
                'erp/payroll',
                'erp/incentive',
                'erp/division',
                'erp/work-schedule',
                'erp/roles',
                'erp/users',
                'erp/audit-log',
                'erp/login-activity',
                'erp/device-management',
            ],
        ],

        'system' => [
            'label' => 'System',
            'active_patterns' => [
                'erp/integrasi',
                'admin',
                'erp/integration/*',
                'erp/company-profile',
                'erp/document-numbering',
                'erp/sync',
                'erp/theme',
                'erp/notifications',
                'erp/api-public',
                'erp/webhook',
                'erp/backup',
                'erp/backup-system',
                'erp/activity-timeline',
                'erp/mobile-sync',
                'erp/payment-gateway',
                'erp/install-app',
            ],
        ],
    ],
];
